### PR TITLE
properties are added

### PR DESCRIPTION
**Pull request by subbarayuduk**
hi sir ,
iam added properties once check it

### CODE REVIEW

**Comment by sagar12ab** [comment]
hi add setters and getters

**Comment by subbarayuduk** [comment]
hi sir  iam added setters and getters check it once

**Comment by subbarayuduk** [comment]
hi sir,
added tostring check it and approve

**Comment by sagar12ab** [comment]
please add constructers

**Comment by subbarayuduk** [comment]
hi constructors added
check it

**Comment by sagar12ab** [comment]
ok commit

**Pull request merged**
